
CREATE TABLE IF NOT EXISTS  MACHINE (
   M_ID INTEGER PRIMARY KEY     AUTO_INCREMENT,
   IDENT          varchar(50)   NOT NULL,
   MNAME          varchar(50)   ,
   IP             varchar(256)  NOT NULL,
   PORT           INT           NOT NULL,
   NPORTS         INT           NOT NULL DEFAULT  1,
   LAST_ACTIVE    LONG          NOT NULL,
   KEYSTR         char(280)     NOT NULL,
);
CREATE UNIQUE      INDEX IF NOT EXISTS MU ON MACHINE(IP, PORT);
CREATE UNIQUE HASH INDEX IF NOT EXISTS MI ON MACHINE(IDENT);











CREATE TABLE IF NOT EXISTS TRACKER (
   T_ID INTEGER PRIMARY KEY     AUTO_INCREMENT,
   IP             varchar(256)  NOT NULL,
   PORT           INT           NOT NULL,
   ENDPORT        INT           NOT NULL,
   LAST_ACTIVE    LONG          NOT NULL,
   KEEPS_FILES    BOOLEAN       NOT NULL,
);
CREATE UNIQUE INDEX IF NOT EXISTS TU ON TRACKER(IP, PORT, ENDPORT);









CREATE TABLE IF NOT EXISTS SFILE (
   F_ID           INTEGER       PRIMARY KEY AUTO_INCREMENT,
   FSIZE          LONG          NOT NULL,
   CHKSUM         char(40)      NOT NULL,
);
CREATE UNIQUE      INDEX IF NOT EXISTS FU ON SFILE(CHKSUM, FSIZE);








CREATE TABLE IF NOT EXISTS MACHINE_CONTAINS (
   MID          INTEGER          NOT NULL,
   FID          INTEGER          NOT NULL,

   FOREIGN KEY(FID) REFERENCES SFILE  (F_ID)  ON DELETE CASCADE,
   FOREIGN KEY(MID) REFERENCES MACHINE(M_ID)  ON DELETE CASCADE,
);
CREATE UNIQUE      INDEX IF NOT EXISTS MCU ON MACHINE_CONTAINS(MID, FID);







CREATE TABLE IF NOT EXISTS RATING_COMMENT (
   C_ID           INTEGER       PRIMARY KEY    AUTO_INCREMENT,
   OID            INTEGER       NOT NULL,
   DID            INTEGER       NOT NULL,
   SENT           LONG          NOT NULL,
   RATING         INTEGER       NOT NULL,
   MESSAGE        varchar(1024) NOT NULL,
   
   FOREIGN KEY(OID) REFERENCES MACHINE(M_ID)  ON DELETE CASCADE,
   FOREIGN KEY(DID) REFERENCES MACHINE(M_ID)  ON DELETE CASCADE,
);
CREATE UNIQUE      INDEX IF NOT EXISTS RC ON RATING_COMMENT(OID, DID);



